
trigger:
- master

#pool: 'Default'
pool: 'AzureVms'

steps:

# Default configuration (on a multiple scenarios folder)-> default parameters are not required 
# The folder contains two scenarios:
#   - 5UsersPassedScenario.lrs
#   - 10UsersPassedScenario.lrs
# Both of them should pass
# - task: ExecMicroFocusTests@0
#   inputs:
#     Test1: 'C:\Scenarios-Multiple\'


- powershell:  
    copy-item -Path C:\IE -Destination $(Build.ArtifactStagingDirectory) -Recurse

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- publish: $(Build.ArtifactStagingDirectory)\IE
  artifact: WebApp

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\IE'
    ArtifactName: 'IE'
    publishLocation: 'FilePath'
    TargetPath: '$(Build.ArtifactStagingDirectory)\IE'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '$(Build.ArtifactStagingDirectory)\IE\*.xml'

