
trigger:
- master

pool: 'Win8.1'
#pool: 'Default'
#pool: 'Win2016'

steps:

- task: ExecuteLoadRunnerTestsRelease@1
  inputs:
    SourcePath: 'C:\Scenarios-None'
    PublishArtifactsManually: true
    PublishTestReportsManually: true