
trigger:
- master

#pool: 'Default'
pool: 'AzureVms'

steps:

# Default configuration (on a multiple scenarios folder)-> default parameters are not required 
# The folder contains two scenarios:
#   - 5UsersPassedScenario.lrs
#   - 10UsersPassedScenario.lrs
# Both of them should pass
# - task: ExecMicroFocusTests@0
#   inputs:
#     Test1: 'C:\Scenarios-Multiple\'


- powershell:  
    copy-item -Path C:\IE -Destination C:\Agent\_work\3\a\IE -Recurse

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'C:\Agent\_work\3\a\IE\*.xml'

- task: FtpUpload@2
  inputs:
    credentialsOption: 'serviceEndpoint'
    rootDirectory: '$(Build.ArtifactStagingDirectory)'
    filePatterns: '**'
    remoteDirectory: '/upload/$(Build.BuildId)/'
    clean: false
    cleanContents: false
    preservePaths: false
    trustSSL: false
