
trigger:
- master

pool: 'Win2019'
#pool: 'Default'
#pool: 'AzureVms'

steps:

# Default configuration (on a multiple scenarios folder)-> default parameters are not required 
# The folder contains two scenarios:
#   - 5UsersPassedScenario.lrs
#   - 10UsersPassedScenario.lrs
# Both of them should pass
- task: ExecMicroFocusTestsDemo7@0
  inputs:
    SourcePath: 'C:\Scenarios-Multiple'
    ResultsDirectory: 'C:\LR'

  