
trigger:
- master

#pool: 'Default'
pool: 'AzureVms'

steps:

# Default configuration (on a multiple scenarios folder)-> default parameters are not required 
# The folder contains two scenarios:
#   - 5UsersPassedScenario.lrs
#   - 10UsersPassedScenario.lrs
# Both of them should pass
# - task: ExecMicroFocusTests@0
#   inputs:
#     Test1: 'C:\Scenarios-Multiple'


- powershell:  
    copy-item -Path C:\IE -Destination .\IE -Recurse

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/*.html'
