
trigger:
- master

pool: 'Win8.1'
#pool: 'Default'
#pool: 'AzureVms'

steps:

- task: ExecMicroFocusTestsDemo8@0
  inputs:
    SourcePath: 'C:\Scenarios-Multiple2'
    PublishScenarioResults: false
    PublishArtifactsManually: true
    PublishTestReportsManually: true