
trigger:
- master

#pool: 'Default'
pool: 'AzureVms'

steps:

# Default configuration (on a multiple scenarios folder)-> default parameters are not required 
# The folder contains two scenarios:
#   - 5UsersPassedScenario.lrs
#   - 10UsersPassedScenario.lrs
# Both of them should pass
# - task: ExecMicroFocusTests@0
#   inputs:
#     Test1: ''

- task: ExecMicroFocusTests@0
  inputs:
    SourcePath: 'C:\Scenarios-Multiple'
    ResultsDirectory: 'C:\LR'
    BuildId: '$(Build.BuildNumber)'
    BuildArtifactsDirectory: '$(Build.ArtifactStagingDirectory)'


# - powershell:  
#     copy-item -Path C:\IE -Destination $(Build.ArtifactStagingDirectory) -Recurse

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\MFTestsArtifacts'
    ArtifactName: 'MFTestsArtifacts'
    publishLocation: 'Container'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '$(Build.ArtifactStagingDirectory)\MFTestsResults\*.xml'

# - task: PublishTestResults@2
#   inputs:
#     testResultsFormat: 'JUnit'
#     testResultsFiles: '$(Build.ArtifactStagingDirectory)\IE\*.xml'

