
trigger:
- master

#pool: 'Default'
pool: 'AzureVms'

steps:

# Default configuration (on a multiple scenarios folder)-> default parameters are not required 
# The folder contains two scenarios:
#   - 5UsersPassedScenario.lrs
#   - 10UsersPassedScenario.lrs
# Both of them should pass
# - task: ExecMicroFocusTests@0
#   inputs:
#     Test1: ''

# - task: ExecMicroFocusTests@0
#   inputs:
#     SourcePath: 'C:\Scenarios-Multiple'
#     ResultsDirectory: 'C:\LR'
#     BuildId: 'Build-$(Build.BuildNumber)'
    # BuildArtifactsDirectory: '$(Build.ArtifactStagingDirectory)'

# - powershell:  
#     copy-item -Path C:\LoadRunnerReports -Destination $(Build.ArtifactStagingDirectory) -Recurse
    
- task: ExecMicroFocusTestsDemo6@0
  inputs:
    SourcePath: 'C:\Scenarios-Multiple'
    ResultsDirectory: 'C:\LR'
    #BuildLabel: 'Build-$(Build.BuildNumber)'


# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)\MFTestsArtifacts'
#     ArtifactName: 'MFTestsArtifacts'
#     publishLocation: 'Container'

# - task: PublishTestResults@2
#   inputs:
#     testResultsFormat: 'JUnit'
#     testResultsFiles: 'C:\Agent\_work\3\a\LoadRunnerReports\*.xml'
#     mergeTestResults: true

# - task: SendEmail@1
#   inputs:
#     To: 'paul-adrian.tofan@microfocus.com'
#     From: 'tofanadrian3000@yahoo.ro'
#     Subject: 'Ice Ice Baby'
#     Body: |
#       Yo, VIP, let's kick it!
#       Ice ice baby
#       Ice ice baby
#       All right stop
#       Collaborate and listen ...
#     BodyAsHtml: false
#     AddAttachment: true
#     Attachment: '$(Build.ArtifactStagingDirectory)\MFTestsArtifacts'